version: '3.5'

services:
  postgres:
    container_name: postgres13_container
    image: postgres:13.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: payment_integration_test
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - shared-network
  
  pgadmin:
    container_name: pgadmin13_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-wayan.sudarma@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5151}:80"
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
    postgres:
    pgadmin: