version: '2'

services:
  master:
    image: redis:8.8.0
    ports:
      - '6379:6379'
  slave:
    image: redis:8.8.0
    command: redis-server --replicaof redis-master 6379
    links:
      - master:redis-master
  sentinel:
    build: sentinel
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_QUORUM=1
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave
